//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhondasPlaceSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candle
    {
        public int CandleID { get; set; }
        public int ImageID { get; set; }
        public int CandleTypeID { get; set; }
        public int CandleSizeID { get; set; }
        public int ScentID { get; set; }
        public int LidID { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string AddUserName { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string LastUpdateUserName { get; set; }
        public bool IsDeleted { get; set; }
        public decimal Price { get; set; }
    
        public virtual CandleSize CandleSize { get; set; }
        public virtual CandleType CandleType { get; set; }
        public virtual Image Image { get; set; }
        public virtual Lid Lid { get; set; }
        public virtual Scent Scent { get; set; }
    }
}
