//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhondasPlaceSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RhondasPlace_1Entities : DbContext
    {
        public RhondasPlace_1Entities()
            : base("name=RhondasPlace_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Candle> Candles { get; set; }
        public virtual DbSet<CandleSize> CandleSizes { get; set; }
        public virtual DbSet<CandleType> CandleTypes { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Lid> Lids { get; set; }
        public virtual DbSet<Scent> Scents { get; set; }
    }
}
